#!/bin/bash

# Stephen Burke - 02.28.2023 - https://github.com/se7enack/ai-computing-assistant

jsonretured=/tmp/.coeus
apifile=$HOME/.coeus
PATH=$PATH:~/opt/bin:/usr/local/bin:/bin:/usr/bin:/opt/homebrew/bin
VTMP=/tmp/.voices
touch $apifile
source $apifile

x=$(ls /System/Library/SpeechBase/Voices | wc -l)
y=$(ls /System/Library/Speech/Voices | wc -l )
if [[ "$x" -gt "$y" ]]; then
  VDIR=/System/Library/SpeechBase/Voices/
else
  VDIR=/System/Library/Speech/Voices/
fi

function grabvoices() {
  cd $VDIR
  VOICES=$(ls $VDIR | grep SpeechVoice)
  rm $VTMP 2> /dev/null
  touch $VTMP
  for VOICE in $VOICES 
  do
    cd $VOICE
    bit=$(plutil -convert xml1 -o - Contents/Info.plist | grep -a1 VoiceShowInFullListOnly | grep -E 'false' > /dev/null)
    if [[ $? -eq "0" ]]; then 
      plutil -convert xml1 -o - Contents/Info.plist | grep -a1 VoiceLocaleIdentifier | grep string | grep "en_" > /dev/null
      if [ "$?" -eq 0 ];then
        name=$(echo -n $VOICE | sed s/"Compact"// | awk -F '.' '{print $1}')
        folder=$(echo $VOICE | awk -F '.' '{print $1}')
        echo "$name $folder $bit" >> $VTMP
      fi
      k=$(plutil -convert xml1 -o - Contents/Info.plist | grep -a1 VoiceLocaleIdentifier)
      if [ "$?" -ne 0 ];then
        name=$(echo -n $VOICE  | sed s/"Compact"// | awk -F '.' '{print $1}')
        folder=$(echo $VOICE | awk -F '.' '{print $1}')
        echo "$name $folder $k" >> $VTMP
      fi
    fi
    cd $VDIR
  done
  available=$(cat $VTMP | awk 'BEGIN {FS=" ";} {printf "'000'%s'000","' ", $1}' | rev | cut -c3- | rev | sed 's/000/\"/g')
  echo "choose from list {$available}"
  choose
  voice=$(cat $VTMP | grep $choice | awk '{print $2}')
}

function youneedkeys() {
  echo "You haven't got an API key yet. Opening a browser to get one." | say -v ${voice}
  open https://platform.openai.com/account/api-keys
  title="Enter Your API Key"
  key="$(promptme)"
  if [ -z "$key" ]; then
    echo "No key entered" | say -v ${voice}
    exit
  else
    echo "export OPENAI_API_KEY=$key" >> $apifile
    source $apifile
  fi 
}

function promptme() {
  osascript <<EOT
    tell app "System Events"
      text returned of (display dialog "$1" default answer "$2" buttons {"OK"} default button 1 with title "${title}")
    end tell
EOT
}

function bad() {
  osascript <<EOT
    tell app "System Events"
      display dialog "$1" buttons {"OK"} default button 1 with icon caution with title "$(basename $0)"
      return  -- Suppress result
    end tell
EOT
}

function dockit() {
  defaults write com.apple.dock persistent-apps -array-add '<dict><key>tile-data</key><dict><key>file-data</key><dict><key>_CFURLString</key><string>/Applications/Coeus.app</string><key>_CFURLStringType</key><integer>0</integer></dict></dict></dict>'
  killall Dock
  touch $jsonretured
}

function getit() {
  image=$HOME/Downloads/${question// /-}.png
  if command -v wget &> /dev/null
  then
    wget -O ${image} ${url} && open ${image}
  else
    curl ${url} --output ${image} && open ${image}
  fi
  start&exit
}

function choose() {
  choice=$(osascript<<EOF
  tell application "System Events"
  activate
  choose from list {$available}
  end tell
EOF)
}

function start() {
  if ! [ -f "$jsonretured" ]; then
    dockit
  fi
  if [[ -z "$OPENAI_API_KEY" ]]; then
    youneedkeys
  fi

  choice=$(osascript<<END
  tell application "System Events"
  activate
  set theAnswer to button returned of (display dialog "AI Generated Search Type" buttons {"Information", "Image", "Exit"})
  end tell
  return theAnswer
  echo $theAnswer
  END)
  
  if [[ "$choice" == "Exit" ]]; then
    exit
  fi

  echo $choice
  title="Coeus: $choice Search"
  question="$(promptme)"
  question=$(echo $question | tr -d "'" | tr -d '"')
  [ -z "$question" ] && echo "Really? You've got nothing?" | say -v ${voice}&&exit

  if [[ "$choice" == "Image" ]]; then
    json="'{\"prompt\": \"${question}\",\"n\": 1,\"size\": \"1024x1024\"}'"
    x=$(echo "curl -s https://api.openai.com/v1/images/generations -H 'Content-Type: application/json' -H 'Authorization: Bearer $OPENAI_API_KEY' -d ${json}")
    bash -c "$x" > $jsonretured  
    if command -v jq &> /dev/null
    then
      cat $jsonretured | grep '"error"' > /dev/null
      if [ "$?" -ne 0 ]; then
        url=$(cat ${jsonretured} | jq -r '.data[].url')
        getit
      else
        badness=$(cat $jsonretured | jq -r .error.message)
        bad "${badness}"
        exit
      fi
    else
      cat $jsonretured | grep '"error"' > /dev/null
      if [ "$?" -ne 0 ]; then
        url=$(cat ${jsonretured} | awk -F '"url":' '{print $2}' | tr -d '"')
        getit
      else
        badness=$(cat ${jsonretured} | awk -F '"message":' '{print $2}' | tr -d '"' | rev | cut -c2- | rev)
        bad "${badness}"
        exit
      fi
    fi
  else
    [ -z "$voice" ] && grabvoices
    json="'{\"model\": \"text-davinci-003\",\"prompt\": \"${question}:\",\"temperature\": 0.9,\"max_tokens\": 3000,\"top_p\": 1,\"frequency_penalty\": 0.0,\"presence_penalty\": 0.6,\"stop\": [\" Human:\", \" AI:\"]}'"
    x=$(echo "curl -s https://api.openai.com/v1/completions -H 'Content-Type: application/json' -H 'Authorization: Bearer $OPENAI_API_KEY' -d ${json}")
    bash -c "$x" > $jsonretured
    if command -v jq &> /dev/null
    then
        msg=$(cat $jsonretured | jq -r '.choices[].text')
    else
        msg=$(cat $jsonretured | awk -F '"text":' '{print $2}' | awk -F 'index' '{print $1}' | rev | cut -c3- | rev | xargs printf)
    fi
    msg2=$(echo "$msg" | sed "s/['\"]//g")
    echo "$msg" | say -v ${voice}&
    echo "tell application \"System Events\"
    activate
    display dialog \"$msg2\" buttons {\"OK\"}
    end tell" | osascript 2>&1
    start&exit
  fi
}

start
